DROP  DATABASE DE4
CREATE  DATABASE DE4
USE DE4

CREATE TABLE GIAOVIEN
(
	IDKHOA int,
	IDMAGV char(4),
	HOTEN nvarchar(30),
	CMND char(9),
	NGSINH datetime,
	IDQL char(4),

	PRIMARY KEY(IDKHOA, IDMAGV)
)
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN FOREIGN KEY (IDKHOA,IDQL) REFERENCES GIAOVIEN(IDKHOA,IDMAGV)

CREATE TABLE LOPHOC
(
	IDLOP char(3),
	NAMBD int,
	CHUNHIEM char(4),
	IDKHOA int,
	SOLUONG int,

	PRIMARY KEY (IDLOP)
)

ALTER TABLE LOPHOC
ADD CONSTRAINT FK_LOPHOC_GIAOVIEN
FOREIGN KEY (IDKHOA,CHUNHIEM)
REFERENCES GIAOVIEN(IDKHOA, IDMAGV)

CREATE TABLE LICHDAY
(
	IDLOP char(3),
	IDTHUTIET char(10),
	IDPHONGHOC int,
	GIAOVIEN char(4),
	IDKHOA int,
	THOILUONG int,
	THIETBI nvarchar(30),

	PRIMARY KEY (IDLOP, IDTHUTIET, IDPHONGHOC)
)
ALTER TABLE LICHDAY
ADD CONSTRAINT FK_LICHDAY_GIAOVIEN
FOREIGN KEY (IDKHOA,GIAOVIEN)
REFERENCES GIAOVIEN(IDKHOA,IDMAGV)

ALTER TABLE LICHDAY
ADD CONSTRAINT FK_LICHDAY_LOPHOC
FOREIGN KEY (IDLOP)
REFERENCES LOPHOC(IDLOP)


INSERT INTO GIAOVIEN (IDKHOA, IDMAGV, HOTEN, CMND, NGSINH,IDQL) 
VALUES 
(1,'1716',N'Nguyễn Quan Tùng', '240674018', '1988-2-1',NULL),
(2,'0357', N'Lưu Phi Nam', '240674027', '1980-7-20', NULL),
(2,'1716', N'Lê Quang Bảo', '240674063', NULL,NULL),
(1,'0753', N'Hà Ngọc Thúy', '240674504', '1990-5-2',NULL),
(1,'0357', N'Trương Thị Minh', '240674405', NULL,NULL),
(1,'1718', N'Ngô Thị Thủy', '240674306', NULL,NULL)


UPDATE GIAOVIEN SET IDQL = '0753' WHERE HOTEN = N'Nguyễn Quan Tùng'
UPDATE GIAOVIEN SET IDQL = '1716' WHERE HOTEN = N'Lưu Phi Nam'
UPDATE GIAOVIEN SET IDQL = '0753' WHERE HOTEN = N'Trương Thị Minh'
UPDATE GIAOVIEN SET IDQL = '0357' WHERE HOTEN = N'Ngô Thị Thủy'

INSERT INTO LOPHOC (IDLOP, NAMBD, CHUNHIEM, IDKHOA, SOLUONG)
VALUES 
('L01',2015,'0357',2,1),
('L02',2013,'1716',1,2)

INSERT INTO LICHDAY (IDLOP, IDTHUTIET, IDPHONGHOC,IDKHOA, GIAOVIEN , THOILUONG, THIETBI)
VALUES
('L01','T2(1-6)',2,1,'1718', 10, N'Máy chiếu'),
('L02','T2(7-12)',1,1,'0753', 30, N'Máy chiếu'),
('L01','T4(4-6)',5,2,'0357', 25, N'Máy chiếu')

SELECT DISTINCT GV.HOTEN, datediff(YYYY,GV.NGSINH,'2023-07-03') as TUOI
FROM GIAOVIEN AS GV, LICHDAY AS LD
WHERE CHARINDEX('6',LD.IDTHUTIET) != 0
ORDER BY TUOI 

SELECT GV.HOTEN AS TENGV, NQL.HOTEN AS NGUOIQUANLY
FROM GIAOVIEN AS GV, GIAOVIEN AS NQL
WHERE NQL.NGSINH IS NULL AND NQL.IDMAGV = GV.IDQL