
-- Create the new database if it does not exist already
IF NOT EXISTS (
    SELECT [name]
        FROM sys.databases
        WHERE [name] = N'QLGiaoVienTGDeTai6'
)
CREATE DATABASE QLGiaoVienTGDeTai6
GO

CREATE TABLE [dbo].[GIAOVIEN]
(
   MAGV NCHAR(4) NOT NULL,
   HOTEN VARCHAR NULL,
   LUONG INT NULL,
   PHAI NCHAR(4) NULL,
   NGSINH DATE NULL,
   DIACHI varchar NULL,
   GVQLCM NCHAR(4) NULL,
   MABM NCHAR(4) NULL,

   PRIMARY KEY (MAGV)
);
GO

CREATE TABLE [dbo].[GV_DT]
(
   MAGV NCHAR(4) NOT NULL,
   DIENTHOAI NCHAR(11) NOT NULL,

   PRIMARY KEY (MAGV, DIENTHOAI),
   FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)
);
GO


CREATE TABLE [dbo].[BOMON]
(
    MABM NCHAR(4) NOT NULL,
    TENBM varchar NULL,
    PHONG NCHAR(3) NULL,
    DIENTHOAI INT NULL,
    TRUONGBM NCHAR(4) NULL,
    MAKHOA NCHAR(4) NULL,
    NGAYNHANCHUC DATE NULL,

    PRIMARY KEY (MABM),
);
GO

CREATE TABLE [dbo].[KHOA]
(
    MAKHOA NCHAR(4) NOT NULL,
    TENKHOA varchar NULL,
    NAMTL INT NULL,
    PHONG NCHAR(4) NULL,
    DIENTHOAI NCHAR(11) NULL,
    TRUONGKHOA NCHAR(4) NULL,
    NGAYNHANCHUC DATE NULL,
    PRIMARY KEY (MAKHOA),
);
GO

CREATE TABLE [dbo].[DETAI]
(
    MADT NCHAR(3) NOT NULL,
    TENDT VARCHAR NULL,
    CAPQL VARCHAR NULL,
    KINHPHI FLOAT(1) NULL,
    NGAYBD DATE NULL,
    NGAYKT DATE NULL,
    MACD NCHAR(4) NULL,
    GVCNDT NCHAR(4) NULL,
    PRIMARY KEY (MADT),
);
GO

CREATE TABLE [dbo].[CHUDE]
(
    MACD NCHAR(4) NOT NULL,
    TENCD VARCHAR NULL,
    PRIMARY KEY (MACD),
);
GO

CREATE TABLE [dbo].[CONGVIEC]
(
    MADT NCHAR(3) NOT NULL,
    STT INT NOT NULL,
    TENCV VARCHAR NULL,
    NGAYBD DATE NULL,
    NGAYKT DATE NULL,
    PRIMARY KEY (MADT, STT),
);
GO

CREATE TABLE [dbo].[THAMGIADT]
(
    MAGV NCHAR(4) NOT NULL,
    MADT NCHAR(3) NOT NULL,
    STT INT NOT NULL,
    PHUCAP FLOAT NULL,
    KETQUA NCHAR(3) NULL,
    PRIMARY KEY(MAGV, MADT, STT),
);
GO

CREATE TABLE [dbo].[NGUOITHAN]
(
    MAGV NCHAR(4) NOT NULL,
    TEN NCHAR(10) NOT NULL,
    NGSINH DATE NULL,
    PHAI NCHAR(3) NULL,
    PRIMARY KEY(MAGV,TEN),
    FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)
);
GO
ALTER TABLE  GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_GIAOVIEN FOREIGN KEY (GVQLCM) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_BOMON FOREIGN KEY (MABM) REFERENCES BOMON(MABM)
ALTER TABLE BOMON ADD CONSTRAINT FK_BOMON_GIAOVIEN FOREIGN KEY (TRUONGBM) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE BOMON ADD CONSTRAINT FK_BOMON_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY (TRUONGKHOA) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE DETAI ADD CONSTRAINT FK_DETAI_CHUDE FOREIGN KEY (MACD) REFERENCES CHUDE(MACD)
ALTER TABLE DETAI ADD CONSTRAINT FK_DETAI_GIAOVIEN FOREIGN KEY (GVCNDT) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE CONGVIEC ADD CONSTRAINT FK_CONGVIEC_DETAI FOREIGN KEY (MADT) REFERENCES DETAI(MADT)
ALTER TABLE THAMGIADT ADD CONSTRAINT FK_THAMGIADT_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE THAMGIADT ADD CONSTRAINT FK_THAMGIADT_CONGVIEC FOREIGN KEY (MADT,STT) REFERENCES CONGVIEC(MADT,STT)
