USE QLGiaoVien

--Q27
SELECT COUNT(*) AS SLGV, SUM(GV.LUONG) AS TONGLUONG
FROM GIAOVIEN AS GV

--Q28
SELECT GV.MABM,COUNT(*) AS SLGV, AVG(GV.LUONG) AS LUONGTRUNGBINH
FROM GIAOVIEN AS GV
GROUP BY GV.MABM

--Q29
SELECT CD.TENCD, COUNT(*) AS SLCD 
FROM CHUDE AS CD, DETAI AS DT
WHERE CD.MACD = DT.MACD
GROUP BY CD.TENCD

--Q30
SELECT GV.HOTEN, COUNT(*) AS SLDT 
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT
WHERE GV.MAGV = TGDT.MAGV
GROUP BY GV.HOTEN

--Q31
SELECT GV.HOTEN, COUNT(*) AS SLDT 
FROM GIAOVIEN AS GV, DETAI AS DT
WHERE GV.MAGV = DT.GVCNDT
GROUP BY GV.HOTEN

--Q32
SELECT GV.HOTEN, COUNT(*) AS SLNT
FROM GIAOVIEN AS GV, NGUOITHAN AS NT
WHERE GV.MAGV = NT.MAGV
GROUP BY GV.HOTEN

--Q33
SELECT GV.HOTEN, COUNT (*) AS SLDT
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT
WHERE GV.MAGV = TGDT.MAGV
GROUP BY GV.HOTEN
HAVING COUNT(*) >= 3

--Q34
SELECT DT.TENDT, COUNT(*) AS SLGV
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, DETAI AS DT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND TGDT.MADT = DT.MADT AND GV.MAGV = TGDT.MAGV 
GROUP BY DT.TENDT