USE QLGiaoVien

--Q1
SELECT HOTEN, LUONG
FROM GIAOVIEN
WHERE PHAI = N'Nữ'

--Q2
SELECT HOTEN, LUONG*0.1 + LUONG AS LUONG
FROM GIAOVIEN

--Q3
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE (CHARINDEX(N'Nguyễn', GV.HOTEN) !=0 AND GV.LUONG > 2000) OR (BM.TRUONGBM = GV.MAGV AND year(BM.NGAYNHANCHUC)>1995)

--Q4
SELECT HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE  GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT'

--Q5
SELECT * 
FROM BOMON AS BM ,GIAOVIEN AS GV 
WHERE BM.TRUONGBM = MAGV

--Q6
SELECT GV.HOTEN, BM.*
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE BM.MABM = GV.MABM

--Q7
SELECT DT.TENDT, GV.HOTEN
FROM DETAI AS DT, GIAOVIEN AS GV
WHERE DT.GVCNDT = GV.MAGV

--Q8
SELECT K.TENKHOA, GV.HOTEN
FROM KHOA AS K, GIAOVIEN AS GV
WHERE K.TRUONGKHOA = GV.MAGV

--Q9
SELECT GV.HOTEN
FROM GIAOVIEN AS GV,BOMON AS BM, DETAI AS DT
WHERE BM.MABM = 'VS' AND DT.MADT = '006' AND GV.MABM = 'VS'

--Q10
SELECT DT.MADT, CD.TENCD, GV.HOTEN, GV.NGSINH, GV.DIACHI
FROM DETAI AS DT, GIAOVIEN AS GV, CHUDE AS CD
WHERE DT.CAPQL = N'Thành phố' AND GV.MAGV = DT.GVCNDT AND CD.MACD = DT.MACD  

--Q11
SELECT GV.HOTEN, NPT.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, GIAOVIEN AS NPT
WHERE GV.MABM = BM.MABM AND BM.TRUONGBM = NPT.MAGV

--Q12
SELECT GV.HOTEN, NPT.HOTEN
FROM GIAOVIEN AS GV, GIAOVIEN AS NPT
WHERE NPT.HOTEN = N'Nguyễn Thanh Tùng' AND  GV.GVQLCM = NPT.MAGV

--Q13
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE BM.TENBM = N'Hệ thống thông tin' AND BM.TRUONGBM = GV.MAGV

--Q14
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT
WHERE MACD = 'QLGD' AND DT.GVCNDT = GV.MAGV

--Q15
SELECT CV.TENCV
FROM DETAI AS DT, CONGVIEC AS CV
WHERE DT.CAPQL = N'ĐHQG' AND CV.MADT = DT.MADT  AND MONTH(CV.NGAYBD) = 3 AND YEAR (CV.NGAYBD) = 2008

--Q16
SELECT GV.HOTEN, NPT.HOTEN
FROM GIAOVIEN AS GV, GIAOVIEN AS NPT
WHERE GV.GVQLCM = NPT.MAGV

--Q17
SELECT CV.TENCV
FROM CONGVIEC AS CV
WHERE MONTH (CV.NGAYBD) < 8 AND MONTH(CV.NGAYBD) > 1 AND YEAR (CV.NGAYBD) =2007

--Q18
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, GIAOVIEN AS TTH
WHERE TTH.HOTEN = N'Trần Trà Hương'  AND GV.MABM = TTH.MABM AND GV.HOTEN != N'Trần Trà Hương'

--Q19
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT, BOMON AS BM
WHERE BM.TRUONGBM = GV.MAGV AND DT.GVCNDT = GV.MAGV

--Q20
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, KHOA AS K, BOMON AS BM
WHERE K.TRUONGKHOA = GV.MAGV AND BM.TRUONGBM = GV.MAGV

--Q21
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT, BOMON AS BM
WHERE BM.TRUONGBM = GV.MAGV AND DT.GVCNDT = GV.MAGV

--Q22
SELECT DISTINCT K.TRUONGKHOA
FROM GIAOVIEN AS GV, KHOA AS K, DETAI AS DT
WHERE K.TRUONGKHOA = DT.GVCNDT AND GV.MAGV = K.TRUONGKHOA

--Q23
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN AS GV, BOMON AS BM, THAMGIADT AS TGDT
WHERE BM.MABM = 'HTTT' AND TGDT.MADT = '001' AND GV.MABM = BM.MABM AND TGDT.MAGV = GV.MAGV

--Q24
SELECT DISTINCT GV.*
FROM GIAOVIEN AS GV, BOMON AS BM, GIAOVIEN AS GV_002
WHERE GV_002.MAGV = '002' AND GV.MABM = GV_002.MABM AND GV.MAGV !='002'

--Q25
SELECT GV.*
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE BM.TRUONGBM = GV.MAGV	

--Q26
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN AS GV
