USE QLGiaoVien
--Q35--
SELECT DISTINCT LUONG AS LUONGCAONHAT
FROM GIAOVIEN 
WHERE LUONG >= ALL(SELECT LUONG 
				   FROM GIAOVIEN)
--Q36--
SELECT HOTEN AS GVLUONGCAONHAT
FROM GIAOVIEN 
WHERE LUONG >= ALL(SELECT LUONG 
				   FROM GIAOVIEN)
--Q37--
SELECT DISTINCT GV.LUONG AS LUONGCAONHAT
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM AND GV.MABM = 'HTTT' AND GV.LUONG >= ALL (SELECT LUONG 
																  FROM GIAOVIEN 
																  WHERE MABM = 'HTTT')
--Q38--
SELECT GV.HOTEN AS GVLONTUOINHAT
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM AND GV.MABM = 'HTTT' AND datediff(y,YEAR(GV.NGSINH),2023) >= ALL (SELECT datediff(y,YEAR(NGSINH),2023) 
																						  FROM GIAOVIEN 
																						  WHERE MABM = 'HTTT')
--Q39--
SELECT GV.HOTEN AS GVNHOTUOINHAT
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT' AND datediff(d,GV.NGSINH,'2023-07-20') <= ALL (SELECT datediff(y,GV2.NGSINH,'2023-07-20') 
																						      FROM GIAOVIEN AS GV2, BOMON AS BM2 
																							  WHERE GV2.MABM = BM2.MABM AND BM2.MAKHOA = 'CNTT')
--Q40--
SELECT GV.HOTEN AS GVLUONGCAONHAT, K.TENKHOA
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K 
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND GV.LUONG >= ALL(SELECT LUONG 
														             FROM GIAOVIEN)
--Q41--
SELECT GV.HOTEN, GV.LUONG, GV.MABM
FROM GIAOVIEN AS GV
WHERE GV.LUONG IN(SELECT MAX(GV2.LUONG) 
				  FROM GIAOVIEN AS GV2 
				  GROUP BY GV2.MABM 
				  HAVING GV.MABM = GV2.MABM)
--Q42--
SELECT DT.TENDT
FROM DETAI AS DT
WHERE DT.MADT NOT IN (SELECT TGDT.MADT 
					  FROM THAMGIADT AS TGDT, GIAOVIEN AS GV 
					  WHERE GV.HOTEN = N'Nguyễn Hoài An' AND TGDT.MAGV = GV.MAGV)
--Q43--
SELECT DT.TENDT, GV.HOTEN AS GVCNDT
FROM DETAI AS DT, GIAOVIEN AS GV
WHERE GV.MAGV = DT.GVCNDT AND DT.MADT NOT IN (SELECT TGDT.MADT 
											  FROM THAMGIADT AS TGDT, GIAOVIEN AS GV2 
											  WHERE GV.HOTEN = N'Nguyễn Hoài An' AND TGDT.MAGV = GV2.MAGV)
--Q44--
SELECT GV.HOTEN 
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT' AND GV.MAGV NOT IN (SELECT TGDT.MAGV 
																   FROM THAMGIADT AS TGDT)
--Q45--
SELECT GV.HOTEN 
FROM GIAOVIEN AS GV
WHERE GV.MAGV NOT IN (SELECT TGDT.MAGV 
					  FROM THAMGIADT AS TGDT)
--Q46--
SELECT HOTEN 
FROM GIAOVIEN 
WHERE LUONG > ALL(SELECT LUONG 
				  FROM GIAOVIEN 
				  WHERE HOTEN =N'Nguyễn Hoài An')
--Q47--
SELECT TBM.*
FROM GIAOVIEN AS TBM, BOMON AS BM
WHERE BM.TRUONGBM = TBM.MAGV AND TBM.MAGV IN (SELECT TGDT.MAGV 
											  FROM THAMGIADT AS TGDT, GIAOVIEN AS GV 
											  WHERE TGDT.MAGV = GV.MAGV 
											  GROUP BY TGDT.MAGV 
											  HAVING COUNT(*) >=1)
--Q48--
SELECT GV1.HOTEN
FROM GIAOVIEN AS GV1, GIAOVIEN AS GV2
WHERE GV1.HOTEN = GV2.HOTEN AND GV1.PHAI = GV2.PHAI AND GV1.MABM = GV2.MABM AND GV1.MAGV != GV2.MAGV 
--Q49--
SELECT *
FROM GIAOVIEN
WHERE LUONG > (SELECT MIN(GV.LUONG) 
			   FROM GIAOVIEN AS GV, BOMON AS BM 
			   WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Công nghệ phần mềm')
--Q50--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.LUONG > ALL(SELECT LUONG 
					 FROM GIAOVIEN 
					 WHERE MABM = 'HTTT')
--Q51--
SELECT K.TENKHOA
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE BM.MABM= GV.MABM AND K.MAKHOA = BM.MAKHOA
GROUP BY K.TENKHOA, K.MAKHOA
HAVING COUNT(GV.MAGV) =
(SELECT MAX(SOLUONGGIAOVIEN)
 FROM (SELECT COUNT(GV.MAGV) AS SOLUONGGIAOVIEN 
       FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K  
	   WHERE BM.MABM= GV.MABM AND K.MAKHOA= BM.MAKHOA 
	   GROUP BY K.MAKHOA) AS TONG
)
--Q52--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT
WHERE DT.GVCNDT = GV.MAGV
GROUP BY GV.HOTEN
HAVING COUNT(DT.GVCNDT) =
(SELECT MAX(SOLUONGCHUNHIEMDT)
 FROM (SELECT COUNT(DT.GVCNDT) AS SOLUONGCHUNHIEMDT 
	   FROM GIAOVIEN AS GV, DETAI AS DT 
	   WHERE DT.GVCNDT = GV.MAGV 
	   GROUP BY DT.GVCNDT) AS TONG
)
--Q53--
SELECT BM.MABM
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = BM.MABM
GROUP BY BM.MABM
HAVING COUNT(GV.MAGV) = 
(SELECT MAX (SOLUONGGIAOVIEN)
 FROM (SELECT COUNT (GV.MAGV) AS SOLUONGGIAOVIEN
	   FROM GIAOVIEN AS GV, BOMON AS BM
	   WHERE GV.MABM = BM.MABM
	   GROUP BY BM.MABM) AS TONG
)
--Q54--
SELECT BM.TENBM, GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, THAMGIADT AS TGDT
WHERE TGDT.MAGV = GV.MAGV AND BM.MABM = GV.MABM 
GROUP BY BM.TENBM, GV.HOTEN
HAVING COUNT(TGDT.MAGV) =
(SELECT MAX(SOLUONGDETAI)
 FROM (SELECT COUNT(TGDT.MAGV) AS SOLUONGDETAI 
	   FROM GIAOVIEN AS GV, BOMON AS BM, THAMGIADT AS TGDT
	   WHERE TGDT.MAGV = GV.MAGV AND BM.MABM = GV.MABM 
	   GROUP BY TGDT.MAGV) AS TONG
)
--Q55--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, THAMGIADT AS TGDT
WHERE TGDT.MAGV = GV.MAGV AND BM.MABM = GV.MABM AND BM.MABM = 'HTTT'
GROUP BY BM.TENBM, GV.HOTEN
HAVING COUNT(TGDT.MAGV) =
(SELECT MAX(SOLUONGDETAI)
 FROM (SELECT COUNT(TGDT.MAGV) AS SOLUONGDETAI 
	   FROM GIAOVIEN AS GV, BOMON AS BM, THAMGIADT AS TGDT
	   WHERE TGDT.MAGV = GV.MAGV AND BM.MABM = GV.MABM AND BM.MABM = 'HTTT'
	   GROUP BY TGDT.MAGV) AS TONG
)
--Q56--
SELECT BM.TENBM, GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, NGUOITHAN AS NT
WHERE NT.MAGV = GV.MAGV AND BM.MABM = GV.MABM 
GROUP BY BM.TENBM, GV.HOTEN
HAVING COUNT(NT.MAGV) =
(SELECT MAX(SOLUONGNGUOITHAN)
 FROM (SELECT COUNT(NT.MAGV) AS SOLUONGNGUOITHAN 
	   FROM GIAOVIEN AS GV, BOMON AS BM, NGUOITHAN AS NT
	   WHERE NT.MAGV = GV.MAGV AND BM.MABM = GV.MABM 
	   GROUP BY NT.MAGV) AS TONG
)
--Q57--
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, DETAI AS DT
WHERE DT.GVCNDT = GV.MAGV AND BM.MABM = GV.MABM AND BM.TRUONGBM = GV.MAGV
GROUP BY BM.TRUONGBM, GV.HOTEN
HAVING COUNT(DT.GVCNDT) =
(SELECT MAX(SOLUONGCHUNHIEMDT)
 FROM (SELECT COUNT(DT.GVCNDT) AS SOLUONGCHUNHIEMDT
	   FROM GIAOVIEN AS GV, BOMON AS BM, DETAI AS DT
	   WHERE DT.GVCNDT = GV.MAGV AND BM.MABM = GV.MABM AND BM.TRUONGBM = GV.MAGV
	   GROUP BY DT.GVCNDT) AS TONG
)
